export const SCAN_STATES = {
  SENDING: 'SENDING',
  SCANNING: 'SCANNING',
  TIER2_SCANNING: 'TIER2_SCANNING',
  CLEAN: 'CLEAN',
  SUSPICIOUS: 'SUSPICIOUS',
  MALWARE: 'MALWARE',
  QUARANTINED: 'QUARANTINED',
};

export default SCAN_STATES;
